name: tests

on:
  push:
    branches:
      - dev
      - jtv/v2
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: linux
            runs-on: ubuntu-22.04
            arch: x86_64

    name: "${{ matrix.os }}-${{ matrix.arch }}"
    runs-on: ${{ matrix.runs-on }}

    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - name: Install Nim
        uses: iffy/install-nim@0ed218de08059d18507144e6aee70e6bad0bc148 # v5.0.3
        with:
          version: "binary:2.0.0"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Avoid rate limiting.

      - name: Install Nimble dependencies
        run: nimble --accept install --depsOnly

      - name: Build
        run: nimble build

      - name: Run tests
        run: ./test
